name = "Hugo Invi"
license = "MIT"
licenselink = "https://github.com/cubiest/hugo-invi/blob/master/LICENSE.txt"
description = "A Hugo adaptation of the Fresh theme from CSS Ninja"
homepage = "https://github.com/cubiest/hugo-invi"
tags = ["responsive", "light", "company", "clean", "landing page"]
features = []
min_version = "0.107"

[author]
  name = "Cubiest"
  homepage = "https://github.com/cubiest"
